
name: Java CI

on: [push]

jobs:
  BuildGradle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up PATH
      run: |
        echo "::add-path::${ANDROID_HOME}/build-tools/30.0.1"
        echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Change wrapper permissions
      run: chmod +x ./gradlew -PgHash=$GITHUB_SHA
    - name: Build mod jar
      run: ./gradlew deploy
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.REPOSITORY_NAME }} + "-Desktop"
        path: Desktop/build/libs/Ozone-Desktop.jar
