
name: Java CI

on: [push, pull_request]

jobs:
  Build-Test:
    runs-on: ubuntu-latest

    steps:
     # Check out current repository
    - name: Fetch Sources
      uses: actions/checkout@v2

    - name: Set up PATH
      run: echo "REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY-Desktop" | awk -F / '{print $2}')" >> $GITHUB_ENV
      
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Change wrapper permissions
      run: chmod +x ./gradlew
  
    # Cache Gradle dependencies
    - name: Setup Gradle Dependencies Cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

    # Cache Gradle Wrapper
    - name: Setup Gradle Wrapper Cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

    - name: Build mod jar
      run: ./gradlew deploy -PgHash="$GITHUB_SHA" -PgBranch="${GITHUB_REF##*/}" -PgRepoOwner="$GITHUB_ACTOR" -PgRepo="$GITHUB_REPOSITORY" -Pbuilder="Github-CI" -PbuilderID="$GITHUB_RUN_ID"
  
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.REPOSITORY_NAME }}
        path: Desktop/build/libs/Ozone-Desktop.jar
    
    - name: Upload Manifest
      uses: actions/upload-artifact@v2
      with:
        name: Ozone-Manifest
        path: src/main/resources/Manifest.properties

    - name: Ozone Test
      run: java -DozoneTest=true -jar Desktop/build/libs/Ozone-Desktop.jar
